### ISSUE TITLE
Can't download datasets

### ISSUE THREAD

**Issue by AndSonder** [vashiegaran/DE-GAN-Implementation-Using-PyTorch#1]
I tried to download the dataset, but I got the following result:
![image](https://user-images.githubusercontent.com/55493212/181462198-86d8f595-ef34-4093-902a-1b619c4c83c2.png)

**Comment by vashiegaran** [comment]
Hi, sorry will reply you in few hours

**Comment by AndSonder** [comment]
> Hi, sorry will reply you in few hours
> […](#)

Thank you very much ! 😄

**Comment by vashiegaran** [comment]
Hi sorry i couldnt find dataset for that, apparently I didnt save on my
local as well. Any other way i can help?

**Comment by AndSonder** [comment]
> Hi sorry i couldnt find dataset for that, apparently I didnt save on my local as well. Any other way i can help?
> […](#)

I will try other way to download the dataset. Thank you.
